# Generated by Django 4.0.5 on 2022-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=500)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('youtube', models.URLField()),
                ('exp_title_1', models.CharField(max_length=50)),
                ('experience_1', models.TextField()),
                ('dur_exp_1', models.CharField(max_length=40)),
                ('exp_title_2', models.CharField(max_length=50)),
                ('experience_2', models.TextField()),
                ('dur_exp_2', models.CharField(max_length=40)),
                ('edu_title_1', models.CharField(max_length=50)),
                ('education_1', models.TextField()),
                ('dur_edu_1', models.CharField(max_length=40)),
                ('edu_title_2', models.CharField(max_length=50)),
                ('education_2', models.TextField()),
                ('dur_edu_2', models.CharField(max_length=40)),
                ('skill_1', models.CharField(max_length=40)),
                ('skill_2', models.CharField(max_length=40)),
                ('skill_3', models.CharField(max_length=40)),
                ('skill_4', models.CharField(max_length=40)),
                ('skill_5', models.CharField(max_length=40)),
                ('interests', models.TextField()),
            ],
        ),
    ]
